Fix [FormChipCell] issues with labels
Taras-Hlukhovetskyi/dashboard-react-controls pull request #3
Opened 2024-02-23 12:45 UTC by Taras-Hlukhovetskyi

https://jira.iguazeng.com/browse/ML-5785

2024-03-06 13:59 UTC, mavdryk requested changes

2024-03-06 13:59 UTC, mavdryk commented on src/lib/components/FormChipCell/NewChipForm/NewChipForm.js
> +
delete empty line

2024-03-06 13:59 UTC, mavdryk commented on src/lib/components/FormChipCell/NewChipForm/NewChipForm.js
> +      (editConfig.chipIndex === chipIndex || !isEditable) && 'edit-chip__icon-close-hidden'
use BEM naming.
`edit-chip__icon-close_hidden`

2024-03-06 13:59 UTC, mavdryk commented on src/lib/components/FormChipCell/FormChipCell.js
> +          isValueFocused: isKeyClicked ? false : true
```suggestion
          isKeyFocused: isKeyClicked,
          isValueFocused: !isKeyClicked
```

2024-03-06 13:59 UTC, mavdryk commented on src/lib/components/FormChipCell/FormChipCell.js
> +          const firstChipSelected = prevState.chipIndex === 0
rename to `firstChipIsSelected`

2024-03-06 13:59 UTC, mavdryk commented on src/lib/components/FormChipCell/FormChipCell.js
> +        const isClickedInsideElement = (pointerCoordinateX, pointerCoordinateY, element) => {
Not sure what element is? is it chip itself or input? use proper name inputElement or chipElement

2024-03-06 13:59 UTC, mavdryk commented on src/lib/types.js
> +  switchOppositeVertical: PropTypes.bool
change props to `autoHorizontalPosition` and `autoVerticalPosition`

2024-03-12 17:51 UTC, Taras-Hlukhovetskyi commented on src/lib/components/FormChipCell/formChipCell.util.js
> +}
NOTE:
I've tried other approaches and nothing worked

2024-03-15 14:46 UTC, mavdryk requested changes

2024-03-15 14:46 UTC, mavdryk commented on src/lib/components/FormChipCell/formChipCell.util.js
> +export const getTextWidth = (elementWitText) => {
typo in the parameter name

2024-03-15 14:46 UTC, mavdryk commented on src/lib/components/FormChipCell/formChipCell.util.js
> +  let span = document.getElementById('chips-hidden-utils-helper-element')
create a variable for the `id`

2024-03-15 14:46 UTC, mavdryk commented on src/lib/components/FormChipCell/formChipCell.util.js
> +  let span = document.getElementById('chips-hidden-utils-helper-element')
rename `span` to `hiddenElement` and the id to `chips-hidden-element`

2024-03-15 14:46 UTC, mavdryk commented on src/lib/components/FormChipCell/formChipCell.util.js
> +    for (const [key, value] of Object.entries(styles)) {
rename to `styleName` and `styleValue`

2024-03-15 14:46 UTC, mavdryk commented on src/lib/components/FormChipCell/formChipCell.util.js
> +  span.textContent = elementWitText.value
add empty line above

2024-03-15 16:26 UTC, closed without merging